Drop database if exists DB_CALL_CENTER;
Create database DB_CALL_CENTER;

Use DB_CALL_CENTER;

Create table TB_FORNECEDOR(
	CD_FORNECEDOR INT NOT NULL AUTO_INCREMENT,
    NM_FORNECEDOR VARCHAR(255) NOT NULL,
    DS_EMAIL VARCHAR(255) NULL,
	DS_RAZAO_SOCIAL VARCHAR(255) NOT NULL,
    DS_CNPJ VARCHAR(255) NOT NULL,
    PRIMARY KEY(CD_FORNECEDOR));
    
Insert into TB_FORNECEDOR values (1, 'Alpargatas', 'alpargatas@teste.com', 'Alpargatas Havainas ', '111');

CREATE TABLE TB_CLIENTE (
	CD_CLIENTE INT NOT NULL AUTO_INCREMENT,
    NM_CLIENTE VARCHAR(255) NOT NULL,
    DS_EMAIL VARCHAR(255) NULL,
    PC_DESCONTO DOUBLE NOT NULL,
    DS_CPF VARCHAR(255) NOT NULL,
    PRIMARY KEY(CD_CLIENTE)
);

CREATE TABLE TB_USUARIO (
	CD_USUARIO INT NOT NULL AUTO_INCREMENT,
    USUARIO VARCHAR(255) NOT NULL,
    SENHA VARCHAR(255) NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PRIMARY KEY(CD_USUARIO)
);

Insert into TB_FORNECEDOR values (1, 'Alessandra', '123', 'alessandra@hotmail.com');